export const commands = [
    // Anime
    { "name": "peek", "desc": "Espiar a alguien.", "alias": ["/peek"], "category": "anime", "uso": "_<mention>_" }, 
    { "name": "comfort", "desc": "Consolar a alguien.", "alias": ["/comfort"], "category": "anime", "uso": "_<mention>_" },
    { "name": "thinkhard", "desc": "Pensar intensamente.", "alias": ["/thinkhard"], "category": "anime", "uso": "_<mention>_" },
    { "name": "curious", "desc": "Sentir curiosidad.", "alias": ["/curious"], "category": "anime", "uso": "_<mention>_" },
    { "name": "sniff", "desc": "Olfatear a alguien.", "alias": ["/sniff"], "category": "anime", "uso": "_<mention>_" },
    { "name": "stare", "desc": "Mirar fijamente.", "alias": ["/stare"], "category": "anime", "uso": "_<mention>_" },
    { "name": "trip", "desc": "Tropezar accidentalmente.", "alias": ["/trip"], "category": "anime", "uso": "_<mention>_" },
    { "name": "blowkiss", "desc": "Lanzar un beso.", "alias": ["/blowkiss"], "category": "anime", "uso": "_<mention>_" },
    { "name": "snuggle", "desc": "Acurrucarse con alguien.", "alias": ["/snuggle"], "category": "anime", "uso": "_<mention>_" },
    {"name": "angry", "desc": "Estar enojado.", "alias": ["/angry"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bleh", "desc": "Sacar la lengua.", "alias": ["/bleh"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bored", "desc": "Estar aburrido.", "alias": ["/bored", "/aburrido"], "category": "anime", "uso": "_<mention>_"},
    {"name": "clap", "desc": "Aplaudir.", "alias": ["/clap"], "category": "anime", "uso": "_<mention>_"},
    {"name": "coffee", "desc": "Tomar café.", "alias": ["/coffee", "/cafe"], "category": "anime", "uso": "_<mention>_"},
    { name: "cold", desc: "Mucho frío.", alias: ["/cold"], category: "anime", uso: "_<mention>_" },
    { name: "sing", desc: "Cantarle a alguien.", alias: ["/sing"], category: "anime", uso: "_<mention>_" },
    { name: "tickle", desc: "Hacer cosquillas.", alias: ["/tickle"], category: "anime", uso: "_<mention>_" },
    { name: "scream", desc: "Gritar fuerte.", alias: ["/scream"], category: "anime", uso: "_<mention>_" },
    { name: "push", desc: "Empujar a alguien.", alias: ["/push"], category: "anime", uso: "_<mention>_" },
    { name: "nope", desc: "Expresar desacuerdo.", alias: ["/nope"], category: "anime", uso: "_<mention>_" },
    { name: "jump", desc: "Saltar de felicidad.", alias: ["/jump"], category: "anime", uso: "_<mention>_" },
    { name: "heat", desc: "Sentir calor.", alias: ["/heat"], category: "anime", uso: "_<mention>_" },
    { name: "gaming", desc: "Jugar videojuegos.", alias: ["/gaming"], category: "anime", uso: "_<mention>_" },
    { name: "draw", desc: "Hacer un dibujo.", alias: ["/draw"], category: "anime", uso: "_<mention>_" },
    { name: "call", desc: "Llamar a alguien.", alias: ["/call"], category: "anime", uso: "_<mention>_" },
    {"name": "dramatic", "desc": "Hacer un drama.", "alias": ["/dramatic", "/drama"], "category": "anime", "uso": "_<mention>_"},
    {"name": "drunk", "desc": "Estar borracho.", "alias": ["/drunk"], "category": "anime", "uso": "_<mention>_"},
    {"name": "impregnate", "desc": "Embarazar.", "alias": ["/impregnate", "/preg"], "category": "anime", "uso": "_<mention>_"},
    {"name": "kisscheek", "desc": "Besar en la mejilla.", "alias": ["/kisscheek", "/beso"], "category": "anime", "uso": "_<mention>_"},
    {"name": "laugh", "desc": "Reírse.", "alias": ["/laugh"], "category": "anime", "uso": "_<mention>_"},
    {"name": "love", "desc": "Sentir atracción.", "alias": ["/love", "/amor"], "category": "anime", "uso": "_<mention>_"},
    {"name": "pout", "desc": "Hacer pucheros.", "alias": ["/pout"], "category": "anime", "uso": "_<mention>_"},
    {"name": "punch", "desc": "Dar un puñetazo.", "alias": ["/punch"], "category": "anime", "uso": "_<mention>_"},
    {"name": "run", "desc": "Correr.", "alias": ["/run", "/correr"], "category": "anime", "uso": "_<mention>_"},
    {"name": "sad", "desc": "Sentir tristeza.", "alias": ["/sad", "/triste"], "category": "anime", "uso": "_<mention>_"},
    {"name": "scared", "desc": "Estar asustado.", "alias": ["/scared"], "category": "anime", "uso": "_<mention>_"},
    {"name": "seduce", "desc": "Seducir.", "alias": ["/seduce"], "category": "anime", "uso": "_<mention>_"},
    {"name": "shy", "desc": "Sentir timidez.", "alias": ["/shy", "/timido"], "category": "anime", "uso": "_<mention>_"},
    {"name": "sleep", "desc": "Dormir.", "alias": ["/sleep"], "category": "anime", "uso": "_<mention>_"},
    {"name": "smoke", "desc": "Fumar.", "alias": ["/smoke", "/fumar"], "category": "anime", "uso": "_<mention>_"},
    {"name": "spit", "desc": "Escupir.", "alias": ["/spit", "/escupir"], "category": "anime", "uso": "_<mention>_"},
    {"name": "step", "desc": "Pisar.", "alias": ["/step", "/pisar"], "category": "anime", "uso": "_<mention>_"},
    {"name": "think", "desc": "Pensar.", "alias": ["/think"], "category": "anime", "uso": "_<mention>_"},
    {"name": "walk", "desc": "Caminar.", "alias": ["/walk"], "category": "anime", "uso": "_<mention>_"},
    {"name": "hug", "desc": "Dar un abrazo.", "alias": ["/hug"], "category": "anime", "uso": "_<mention>_"},
    {"name": "kill", "desc": "Asesinar.", "alias": ["/kill"], "category": "anime", "uso": "_<mention>_"},
    {"name": "eat", "desc": "Comer.", "alias": ["/eat", "/nom", "/comer"], "category": "anime", "uso": "_<mention>_"},
    {"name": "kiss", "desc": "Dar un beso.", "alias": ["/kiss", "/muak"], "category": "anime", "uso": "_<mention>_"},
    {"name": "wink", "desc": "Guiñar.", "alias": ["/wink"], "category": "anime", "uso": "_<mention>_"},
    {"name": "pat", "desc": "Dar una caricia.", "alias": ["/pat"], "category": "anime", "uso": "_<mention>_"},
    {"name": "happy", "desc": "Saltos de felicidad.", "alias": ["/happy", "/feliz"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bully", "desc": "Hacer bullying.", "alias": ["/bully"], "category": "anime", "uso": "_<mention>_"}, 
    {"name": "bite", "desc": "Morder.", "alias": ["/bite", "/morder"], "category": "anime", "uso": "_<mention>_"},
    {"name": "blush", "desc": "Sonrojarse.", "alias": ["/blush"], "category": "anime", "uso": "_<mention>_"},
    {"name": "wave", "desc": "Saludar.", "alias": ["/wave"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bath", "desc": "Bañarse.", "alias": ["/bath"], "category": "anime", "uso": "_<mention>_"},
    {"name": "smug", "desc": "Presumir.", "alias": ["/smug"], "category": "anime", "uso": "_<mention>_"},
    {"name": "smile", "desc": "Sonreír.", "alias": ["/smile"], "category": "anime", "uso": "_<mention>_"},
    {"name": "highfive", "desc": "Chocar los cinco.", "alias": ["/highfive"], "category": "anime", "uso": "_<mention>_"},
    {"name": "handhold", "desc": "Tomar de la mano.", "alias": ["/handhold"], "category": "anime", "uso": "_<mention>_"},
    {"name": "cringe", "desc": "Sentir cringe.", "alias": ["/cringe"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bonk", "desc": "Golpear.", "alias": ["/bonk"], "category": "anime", "uso": "_<mention>_"},
    {"name": "cry", "desc": "Llorar.", "alias": ["/cry"], "category": "anime", "uso": "_<mention>_"},
    {"name": "lick", "desc": "Lamer.", "alias": ["/lick"], "category": "anime", "uso": "_<mention>_"},
    {"name": "slap", "desc": "Dar una bofetada.", "alias": ["/slap"], "category": "anime", "uso": "_<mention>_"},
    {"name": "dance", "desc": "Bailar.", "alias": ["/dance"], "category": "anime", "uso": "_<mention>_"},
    {"name": "cuddle", "desc": "Acurrucarse.", "alias": ["/cuddle"], "category": "anime", "uso": "_<mention>_"},

    // Download
    {"name": "facebook", "desc": "Descarga videos de facebook.", "alias": ["/facebook", "/fb"], "category": "download", "uso": "_<url>_"},
    {"name": "instagram", "desc": "Descarga videos de instagram.", "alias": ["/instagram", "/ig", "/reel"], "category": "download", "uso": "_<url>_"},
    {"name": "tiktok", "desc": "Descarga videos de tiktok.", "alias": ["/tiktok", "/tt"], "category": "download", "uso": "_<url|query>_"},
    {"name": "ytmp3", "desc": "Descarga videos de youtube.", "alias": ["/play", "/mp3", "/playaudio", "/ytaudio", "/ytmp3"], "category": "download", "uso": "_<url|query>_"},
    {"name": "spotify", "desc": "Descarga audios de spotify.", "alias": ["/spotify", "/sp"], "category": "download", "uso": "_<url|query>_"},
    {"name": "ytmp4", "desc": "Descarga videos de youtube.", "alias": ["/play2", "/mp4", "/playvideo", "/ytvideo", "/ytmp4"], "category": "download", "uso": "_<url|query>_"},
    { "name": "mf", "desc": "Descarga archivos desde Mediafire.", "alias": ["/mf", "/mediafire"], "category": "download", "uso": "_<url>_" },

    // ECONOMÍA
    {"name": "balance", "desc": "Muestra tu balance o la de un usuario.", "alias": ["/balance", "/bal"], "category": "economia", "uso": "_<mention>_" },
    {"name": "steal", "desc": "Intenta robar coins a un usuario.", "alias": ["/steal", "/rob", "/robar"], "category": "economia", "uso": "_<mention>_" },
    {"name": "slot", "desc": "Apostar coins en el casino.", "alias": ["/slot"], "category": "economia", "uso": "_<cantidad>_" },
    {"name": "fish", "desc": "Ganar coins pescando.", "alias": ["/fish", "/pezcar"], "category": "economia" },
    {"name": "cazar", "desc": "Intenta cazar un animal para ganar coins.", "alias": ["/cazar", "/hunt"], "category": "economia" },
    {"name": "dungueon", "desc": "Explorar mazmorra para ganar Coins.", "alias": ["/gungeon", "/mazmorra"], "category": "economia" },
    {"name": "crime", "desc": "Intenta cometer un crimen.", "alias": ["/crime"], "category": "economia" },
    { "name": "ritual", "desc": "Invoca un ritual misterioso con recompensas o maldiciones.", "alias": ["/ritual"], "category": "economia" },
    {"name": "givecoins", "desc": "Regala coins a un usuario.", "alias": ["/givecoins", "/pay", "/coinsgive"], "category": "economia", "uso": "_<cantidad|all>_ + _<mention>_" },
    {"name": "ppt", "desc": "Juega a piedra, papel o tijera con el bot y gana o pierde coins.", "alias": ["/ppt"], "category": "economia", "uso": "_<piedra|papel|tijera>_" },
    {"name": "waittimes", "desc": "Muestra tus tiempos de enfriamiento en las acciones de RPG.", "alias": ["/waittimes", "/cooldowns", "/economyinfo", "/einfo"], "category": "economia" },
    {"name": "economyboard", "desc": "Consulta el ranking de coins en el grupo.", "alias": ["/economyboard", "/baltop", "/eboard"], "category": "economia", "uso": "_<página>_" },
    {"name": "slut", "desc": "Prostitúyate y gana coins.", "alias": ["/slut"], "category": "economia" },
    {"name": "mine", "desc": "Realiza trabajos de minería y gana coins.", "alias": ["/mine"], "category": "economia" },
    { "name": "rt", "desc": "Apuesta coins en la ruleta de colores y prueba tu suerte.", "alias": ["/rt", "/roulette", "/ruleta"], "category": "economia", "uso": "_<cantidad>_ + _<red|black|green>_" },
    {"name": "coinflip", "desc": "Apuesta coins a cara o cruz.", "alias": ["/coinflip", "/flip", "/cf"], "category": "economia", "uso": "_<bet>_" },
    {"name": "daily", "desc": "Reclama tu recompensa diaria.", "alias": ["/daily"], "category": "economia" },
    {"name": "work", "desc": "Realiza un trabajo y gana coins.", "alias": ["/work", "/w"], "category": "economia" },
    { "name": "math", "desc": "Inicia un juego de matemáticas.", "alias": ["/math", "/matematicas"], "category": "economia", "uso": "_<dificultad>_" },
    {"name": "deposit", "desc": "Deposita coins en tu banco.", "alias": ["/deposit", "/dep", "/d"], "category": "economia", "uso": "_<cantidad|all>_" },
    {"name": "withdraw", "desc": "Retira coins de tu banco.", "alias": ["/withdraw", "/with"], "category": "economia", "uso": "_<cantidad|all>_" },
    {"name": "ahorcado", "desc": "Completa la palabra antes de terminar ahorcado.", "alias": ["/hangman", "/ahorcado"], "category": "economia" },
    {"name": "carrera", "desc": "Apuesta a uno de los 6 caballos y gana recompensas.", "alias": ["/carrera"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "conecta4", "desc": "Juega contra tu amigo o contra el bot a conectar 4 bolas.", "alias": ["/c4", "/conecta4", "/connet4"], "category": "economia", "uso": "_<mencion>_"},
    {"name": "carrera", "desc": "Apuesta a uno de los 6 caballos y gana recompensas.", "alias": ["/carrera"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "duelo", "desc": "Realiza un duelo contra el bot o contra tu amigo.", "alias": ["/duelo"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "higerorlower", "desc": "Apuesta y adivina si la siguente carta es alta o baja.", "alias": ["/higerorlower", "/hol", "/higher", "/lower", "/holcobrar"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "modoimpuestos", "desc": "Activa o desactiva el modo impuestos en el grupo", "alias": ["/modoimpuestos on | off"], "category": "economia", "uso": "_<on / off>_"},
    {"name": "setimpuestos", "desc": "Decide a que hora se activan los impuestos.", "alias": ["/setimpuesto"], "category": "economia", "uso": "_<hora>_"},
    {"name": "impuestos", "desc": "Recibe informacion de cuanto debes pagar.", "alias": ["/impuestos"], "category": "economia"},
    {"name": "lumbox", "desc": "Abre una lumbox para recibir recompensas", "alias": ["/lumbox", "/luckbox"], "category": "economia"},
    {"name": "memoria", "desc": "Juega con el bot o con tu amigo a encotnrar par de emojis.", "alias": ["/memoria", "/memory"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "buscaminas", "desc": "Apuesta y juega al clasico buscaminas.", "alias": ["/buscaminas", "/mineweper"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "plinko", "desc": "Apuesta en el juego de plinko.", "alias": ["/plinko"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "simin", "desc": "Apuesta y juega al juego de simon memorisando numeros.", "alias": ["/simon"], "category": "economia", "uso": "_<apuesta>_"},
    {"name": "slot", "desc": "Apuesta en la ruleta.", "alias": ["/slot"], "category": "economia", "uso": "_<apuesta>_"},

    // Gacha
    {"name": "rw", "desc": "Envia waifus aleatorios con valor.", "alias": ["/rw", "/roll", "/rollwaifu", "/rf"], "category": "gacha"},
    {"name": "c", "desc": "Compra una waifu.", "alias": ["/c", "/claim"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "harem", "desc": "Mira tus personajes obtenidos.", "alias": ["/harem", "/miswaifus", "/claims"], "category": "gacha"},
    {"name": "sell", "desc": "Vende una waifu y gana coins.", "alias": ["/sell", "/vender"], "category": "gacha", "uso": "_<waifu>_ + _<value>_"},
    {"name": "buyc", "desc": "Compra una waifu de la tienda.", "alias": ["/buyc", "/buycharacter", "/buychar"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "trade", "desc": "Intercambia una waifu por otra waifu.", "alias": ["/trade", "/cambiar"], "category": "gacha", "uso": "_<tu personaje / personaje 2>_"},
    {"name": "animelist", "desc": "Lista series del socket.", "alias": ["/animelist", "/slist", "/serielist"], "category": "gacha"},
    {"name": "animeinfo", "desc": "Información de un anime.", "alias": ["/animeinfo", "/ainfo", "/serieinfo"], "category": "gacha", "uso": "_<anime>_"},
    {"name": "tiendawaifus", "desc": "Verifica las waifus en ventas.", "alias": ["/tiendawaifus", "/wshop", "/haremshop"], "category": "gacha"},
    {"name": "deletechar", "desc": "Elimina una waifu de tu obtenidos.", "alias": ["/deletechar", "/delwaifu", "/delchar"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "removerventa", "desc": "Elimina una waifu de la venta.", "alias": ["/removerventa", "/removesale"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "givechar", "desc": "Regala una waifu a un usuario.", "alias": ["/givechar", "/regalar", "/givewaifu"], "category": "gacha", "uso": "_<mention>_ + _<waifu>_"},
    {"name": "giveallharem", "desc": "Regala todas tus waifus a un usuario.", "alias": ["/giveallharem"], "category": "gacha", "uso": "_<mention>_"},
    {"name": "ginfo", "desc": "Ver los enfriamientos de los juegos gacha.", "alias": ["/ginfo", "/infogacha", "/gachainfo"], "category": "gacha"},
    {"name": "winfo", "desc": "Ver la información de una waifu.", "alias": ["/winfo", "/charinfo", "/cinfo"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "wimage", "desc": "Ver la imagen de una waifu.", "alias": ["/wimage", "/charimage", "/cimage"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "vote", "desc": "Votar por una waifu y subir su valor.", "alias": ["/vote", "/votar"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "accepttrade", "desc": "Aceptar un intercambio de harems.", "alias": ["/accepttrade", "/aceptarintercambio"], "category": "gacha", "uso": "_<solicitud>_"},
    {"name": "waifusboard", "desc": "Ver los usuarios con más waifus.", "alias": ["/waifusboard", "/topwaifus", "/waifustop"], "category": "gacha", "uso": "_<mention>_"},
    {"name": "aventura", "desc": "Realiza aventuras con tus waifus y gana recompensas.", "alias": ["/aventura"], "category": "gacha"},
    {"name": "baúl", "desc": "Guarda tus personajes en el baúl.", "alias": ["/guardar", "/sacar"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "bodas", "desc": "Casate con tu waifu.", "alias": ["/casarw", "/marrygacha"], "category": "gacha", "uso": "_<waifu>_"},
    {"name": "divorcio", "desc": "Divorciate de tu waifu.", "alias": ["/rwdivorce", "/divorcerw", "/separar"], "category": "gacha"},
    {"name": "robar", "desc": "Ronale una waifu a alguien.", "alias": ["/robarp", "/robarpersonaje", "/robarrw"], "category": "gacha", "uso": "_<mention>_"},
    {"name": "topvotos", "desc": "Ver el top de las waifus mas votadas por los usuarios.", "alias": ["/topvotos", "/topvote", "/gtv", "/globaltopvotos"], "category": "gacha"},
    {"name": "verpersonaje", "desc": "Ver el o los personajes del bot.", "alias": ["/vp", "/verpersonaje"], "category": "gacha", "uso": "_<waifu>_"},

    // Grupo
    {"name": "bot", "desc": "Activa y desactiva el bot en el grupo.", "alias": ["/bot"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "promote", "desc": "Promueve a un usuario a administrador.", "alias": ["/promote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "demote", "desc": "Degrada a un usuario de administrador.", "alias": ["/demote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "setprimary", "desc": "Establece un bot como primario del grupo.", "alias": ["/setprimary"], "category": "grupo", "uso": "_<mention>_"},
    { "name": "warn", "desc": "Añade una advertencia a un usuario del grupo.", "alias": ["/warn"], "category": "grupo", "uso": "_<mention>_ + _<razón>_" },
    {"name": "topcount", "desc": "Top de usuarios con mas mensajes.", "alias": ["/topcount", "/topmessages", "/topmensajes", "/topmsgcount"], "category": "grupo"},
   { "name": "setwelcome", "desc": "Configura un mensaje de bienvenida.", "alias": ["/setwelcome"], "category": "grupo" },
    { "name": "setbye", "desc": "Configura un mensaje de despedida.", "alias": ["/setbye"], "category": "grupo" },
    { "name": "warns", "desc": "Muestra todas las advertencias registradas de un usuario.", "alias": ["/warns"], "category": "grupo", "uso": "_<mention>_" },
    { "name": "delwarn", "desc": "Elimina una advertencia específica de un usuario.", "alias": ["/delwarn"], "category": "grupo", "uso": "_<mention> <número|all>_" },
    { "name": "setwarnlimit", "desc": "Establece el límite máximo de advertencias permitidas en el grupo.", "alias": ["/setwarnlimit"], "category": "grupo", "uso": "_<número>_" },
    {"name": "clear", "desc": "Elimina usuarios inactivos tras 30 días, o consulta actividad con 'views'", "alias": ["/clear"], "category": "grupo", "uso": "_<delete|views>_"},
    {"name": "setgpbaner", "desc": "Cambia la imagen del grupo.", "alias": ["/setgpbaner"], "category": "grupo"},
    {"name": "setgpname", "desc": "Cambia el nombre del grupo.", "alias": ["/setgpname"], "category": "grupo", "uso": "_<text>_"},
    {"name": "setgpdesc", "desc": "Cambia la descripción del grupo.", "alias": ["/setgpdesc"], "category": "grupo", "uso": "_<text>_"},
    { name: "closet", desc: "Permite cerrar o abrir el grupo de forma inmediata o programada.", alias: ["/closet", "/open"], category: "grupo", uso: "_<tiempo>_" },
    {"name": "options", "desc": "Desactiva o activa las configuraciones del grupo.", "alias": ["/welcome", "/bienvenidas", "/antistatus", "/antiestados", "/alerts", "/alertas", "/gacha", "/rpg", "/pokes", "/economy", "/economia", "/adminonly", "/onlyadmin", "/antilinks", "/antilink", "/antienlaces", "/goodbye", "/antinsfw", "/antiporno", "/despedidas", "/bye"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "groupinfo", "desc": "Muestra la información del grupo.", "alias": ["/groupinfo", "/gp"], "category": "grupo"},
    {"name": "tag", "desc": "Menciona a todos los usuarios del grupo.", "alias": ["/tag", "/hidetag"], "category": "grupo", "uso": "_<text>_"},
    {"name": "kick", "desc": "Expulsa a un usuario del grupo.", "alias": ["/kick"], "category": "grupo", "uso": "_<mention>_"},

    // IA
    {"name": "ia", "desc": "Realiza una petición a chatgpt.", "alias": ["/ia", "/chatgpt"], "category": "ia", "uso": "_<query>_"},
   { "name": "nanobanana", "desc": "Genera una imagen con la API de Nanobanana a partir de un prompt.", "alias": ["/nano"], "category": "ia", "uso": "_<prompt>_" },
   { "name": "genmusic", "desc": "Genera canciones a partir de un prompt.", "alias": ["/genmusic"], "category": "ia", "uso": "_<prompt>_" },
   { "name": "suno2", "desc": "Genera canciones a partir de letra y  un prompt.", "alias": ["/genmusic2"], "category": "ia", "uso": "_<letra | prompt>_" },

    // Info
    { "name": "allmenu", "desc": "Muestra la lista de comandos.", "alias": ["/allmenu", "/menu", "/help"], "category": "info", "uso": "_<category>_" },
    {"name": "infobot", "desc": "Muestra la información del socket.", "alias": ["/infobot", "/infosocket", "/info"], "category": "info"},
    {"name": "ping", "desc": "Muestra la velocidad del Bot.", "alias": ["/ping", "/p"], "category": "info"},
    {"name": "report", "desc": "Envia un mensaje de reporte al Staff.", "alias": ["/report", "/reporte"], "category": "info", "uso": "_<error>_"},
    {"name": "status", "desc": "Ver el estado del Bot.", "alias": ["/status"], "category": "info"},
    {"name": "sug", "desc": "Envia un mensaje de sugerencia al Staff.", "alias": ["/sug", "/suggest"], "category": "info", "uso": "_<suggest>_"},
    {"name": "invite", "desc": "Envia una sugerencia de un grupo a los moderadores.", "alias": ["/invitar", "/invite"], "category": "info", "uso": "_<link>_"},

    // NSFW
    { "name": "xnxx", "desc": "Busca y descarga videos desde XNXX.", "alias": ["/xnxx"], "category": "nsfw", "uso": "_<query|url>_" },
    { "name": "xvideos", "desc": "Busca y descarga videos desde XVideos.", "alias": ["/xvideos"], "category": "nsfw", "uso": "_<query|url>_" },
    {"name": "danbooru", "desc": "Buscar imágenes en danbooru.", "alias": ["/danbooru", "/dbooru"], "category": "nsfw", "uso": "_<tag>_"},
    { "name": "rule34", "desc": "Buscar imágenes o videos en Rule34.", "alias": ["/r34", "/r34vid", "/rule34", "/rule34vid", "/rule", "/rulevid"], "category": "nsfw", "uso": "_<tag>_" },
    {"name": "gelbooru", "desc": "Buscar imágenes en gelbooru.", "alias": ["/gelbooru", "/gbooru"], "category": "nsfw", "uso": "_<tag>_"},
    {"name": "fap", "desc": "Hacerse una paja.", "alias": ["/fap", "/paja"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "anal", "desc": "Hacer un anal.", "alias": ["/anal"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "grabboobs", "desc": "Agarrar las tetas de un usuario.", "alias": ["/grabboobs"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "footjob", "desc": "Hacer una paja con los pies a un usuario.", "alias": ["/footjob"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "grope", "desc": "Manosear las nalgas de un usuario.", "alias": ["/grope"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "undress", "desc": "Encuerate o encuera a un usuario.", "alias": ["/undress", "/encuerar"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "sixnine", "desc": "Hacer un 69 con un usuario.", "alias": ["/sixnine", "/69"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "lickpussy", "desc": "Lamer un coño de un usuario.", "alias": ["/lickpussy"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "spank", "desc": "Darle una nalgada a un usuario.", "alias": ["/spank", "/nalgada"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "fuck", "desc": "Coger a un usuario.", "alias": ["/fuck", "/coger"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "suckboobs", "desc": "Chupar las tetas de un usuario.", "alias": ["/suckboobs", "/chupartetas"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "yuri", "desc": "Hacer tijeras con un usuario.", "alias": ["/yuri", "/tijeras"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "cummouth", "desc": "Corrida en la boca de un usuario.", "alias": ["/cummouth"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "cumshot", "desc": "Eyacular sobre un usuario.", "alias": ["/cumshot"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "lickdick", "desc": "Lamer la polla de un usuario.", "alias": ["/lickdick", "/lamerpolla"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "lickass", "desc": "Lamer el culo de un usuario.", "alias": ["/lickass", "/lamercullo"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "handjob", "desc": "Hacer una paja manual a un usuario.", "alias": ["/handjob"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "blowjob", "desc": "Dar una mamada a un usuario.", "alias": ["/blowjob", "/mamar", "/bj"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "boobjob", "desc": "Hacer una rusa a un usuario.", "alias": ["/boobjob", "/rusa"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "cum", "desc": "Eyacular dentro de un usuario.", "alias": ["/cum", "/eyacular"], "category": "nsfw", "uso": "_<mention>_"},

    // Perfil
    {"name": "level", "desc": "Muestra información de tu nivel y progreso.", "alias": ["/level", "/levelup", "/lvl"], "category": "profile", "uso": "_<mention>_"},
    {"name": "count", "desc": "Ver tus contadores de mensajes.", "alias": ["/count", "/mensajes", "/message", "/msgcount"], "category": "profile", "uso": "_<mention>_"},
    {"name": "marry", "desc": "Envia una solicitud de matrimonio a un usuario.", "alias": ["/marry"], "category": "profile", "uso": "_<mention>_"},
    {"name": "divorce", "desc": "Divorciate de tu pareja.", "alias": ["/divorce"], "category": "profile"},
    {"name": "profile", "desc": "Muestra tu perfil o la de un usuario.", "alias": ["/profile", "/perfil"], "category": "profile"},
    {"name": "setbirth", "desc": "Define una fecha de nacimiento a tu perfil.", "alias": ["/setbirth"], "category": "profile", "uso": "_<dia/mes/año|mes/dia>_"},
    { "name": "setpasatiempo", "desc": "Establece o cambia tu pasatiempo en el perfil.", "alias": ["/setpasatiempo", "/sethobby"], "category": "profile" },
    {"name": "delbirth", "desc": "Elimina tu fecha de nacimiento actual del perfil.", "alias": ["/delbirth"], "category": "profile"},
    { "name": "delpasatiempo", "desc": "Elimina tu pasatiempo actual del perfil.", "alias": ["/delpasatiempo", "/removehobby"], "category": "profile" },
    {"name": "setdescription", "desc": "Define una descripción a tu perfil.", "alias": ["/setdescription", "/setdesc"], "category": "profile", "uso": "_<text>_"},
    {"name": "deldescription", "desc": "Elimina tu descripción actual del perfil.", "alias": ["/deldescription", "/deldesc"], "category": "profile"},
    {"name": "setgenre", "desc": "Define un género a tu perfil.", "alias": ["/setgenre"], "category": "profile", "uso": "_<hombre|mujer>_"},
    {"name": "delgenre", "desc": "Elimina tu género actual del perfil.", "alias": ["/delgenre"], "category": "profile"},

    // Búsqueda
    {"name": "pinterest", "desc": "Busca imágenes en pinterest.", "alias": ["/pinterest", "/pin"], "category": "search", "uso": "_<query>_"},
    { "name": "applemusicsearch", "desc": "Busca informacion en Apple Music.", "alias": ["/applemusicsearch", "/ams"], "category": "search", "uso": "_<query>_"},
    {"name": "imagen", "desc": "Busca imágenes en Google.", "alias": ["/imagen", "/img"], "category": "search", "uso": "_<query>_"},
    {"name": "wikipedia", "desc": "Busca información en Wikipedia.", "alias": ["/wikipedia", "/wiki"], "category": "search", "uso": "_<query>_"},
    {"name": "aptoide", "desc": "Descarga aplicaciones de aptoide.", "alias": ["/aptoide", "/apk", "/apkdl"], "category": "search", "uso": "_<query>_"},
    {"name": "ytsearch", "desc": "Busca videos de youtube.", "alias": ["/ytsearch", "/search"], "category": "search", "uso": "_<query>_"},
    {"name": "tiktoksearch", "desc": "Busca videos de tiktok.", "alias": ["/ttsearch", "/tiktoksearch", "/tts"], "category": "search", "uso": "_<query>_"},

    // Sockets
    {"name": "bots", "desc": "Muestra el número de sockets conectados.", "alias": ["/bots", "/sockets"], "category": "sockets"},
    {"name": "code", "desc": "Vincular un nuevo socket a tu número.", "alias": ["/code", "/qr"], "category": "sockets"},
    {"name": "codepremium", "desc": "Vincular un nuevo socket de tipo prem a tu número.", "alias": ["/codepremium", "/qrpremium"], "category": "sockets", "uso": "_<token>_" },
    {"name": "codemod", "desc": "Vincular un nuevo socket de tipo mod a tu número.", "alias": ["/codemod", "/qrmod"], "category": "sockets", "uso": "_<token>_" },
    {"name": "self", "desc": "Haz privado o público tu socket.", "alias": ["/self"], "category": "sockets", "uso": "_<on|off>_"},
    { "name": "setbanner", "desc": "Cambiar el banner del menu.", "alias": ["/setbanner", "/setmenubanner"], "category": "sockets" },
    { "name": "join", "desc": "Unir el bot a un grupo.", "alias": ["/join", "/unir"], "category": "sockets", "uso": "_<enlace>_" },
    { "name": "seticon", "desc": "Cambiar el icon del socket.", "alias": ["/seticon"], "category": "sockets" },
    { "name": "setbotname", "desc": "Cambiar el nombre del bot.", "alias": ["/setbotname", "/setname"], "category": "sockets", "uso": "_<corto / largo>_" },
    { "name": "setbotowner", "desc": "Cambiar el dueño del bot.", "alias": ["/setbotowner"], "category": "sockets", "uso": "_<nombre|número>_" },
    { "name": "setbotcurrency", "desc": "Cambiar la moneda del bot.", "alias": ["/setbotcurrency"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setbotprefix", "desc": "Cambiar el prefijo del bot.", "alias": ["/setbotprefix"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setbotlink", "desc": "Cambiar el enlace del bot.", "alias": ["/setbotlink", "/setlink"], "category": "sockets", "uso": "_<value>_" },
    { "name": "logout", "desc": "Elimina la sessión del bot.", "alias": ["/logout"], "category": "sockets" },
    { "name": "reload", "desc": "Recarga la sesion del bot.", "alias": ["/reload"], "category": "sockets" },
    { "name": "setusername", "desc": "Cambia el nombre de usuario.", "alias": ["/setusername"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setstatus", "desc": "Actualiza el estado del bot.", "alias": ["/setstatus"], "category": "sockets", "uso": "_<value>_" },
    { "name": "setpfp", "desc": "Cambiar la imagen de perfil.", "alias": ["/setpfp", "/setimage"], "category": "sockets" },
    {"name": "leave", "desc": "El bot abandona el grupo actual.", "alias": ["/leave"], "category": "sockets"},

    // Stickers
    {"name": "setmeta", "desc": "Define los metadatos para tus stickers.", "alias": ["/setmeta", "/setstickermeta"], "category": "stickers", "uso": "_<packname> | <author>_"},
  { "name": "setpackname", "desc": "Renombra uno de tus paquetes de stickers.", "alias": ["/setstickerpackname", "/setpackname", "/packname"], "category": "stickers", "uso": "_<pack> | <nuevoname>_" },
    {"name": "sticker", "desc": "Convierte imágenes o videos a stickers.", "alias": ["/sticker", "/s"], "category": "stickers", "uso": "_<pack>_ + | + _<autor>_"},
     { "name": "stickerpack", "desc": "Busca y descarga packs de Stickers.", "alias": ["/stickerpack", "/spack"], "category": "stickers", "uso": "_<query>_" },
  { "name": "packdesc", "desc": "Cambiar la descripción de un paquete de stickers.", "alias": ["/packdesc", "/setpackdesc", "/setstickerpackdesc"], "category": "stickers", "uso": "_<paquete>_ + | + _<descripción>_" },
  { "name": "packprivate", "desc": "Establecer un paquete de stickers como privado.", "alias": ["/packprivate", "/setpackpriv", "/setpackprivate"], "category": "stickers", "uso": "_<paquete>_" },
  { "name": "packpublic", "desc": "Establecer un paquete de stickers como público.", "alias": ["/packpublic", "/setpackpub", "/setpackpublic"], "category": "stickers", "uso": "_<paquete>_" },
  { "name": "packlist", "desc": "Listar todos tus paquetes de stickers.", "alias": ["/packlist", "/stickerpacks"], "category": "stickers" },
  { "name": "newpack", "desc": "Crear un nuevo paquete de stickers.", "alias": ["/newpack", "/newstickerpack"], "category": "stickers", "uso": "_<paquete>_" },
  { "name": "getpack", "desc": "Obtener un paquete de stickers (propio o público).", "alias": ["/getpack", "/pack", "/stickerpack"], "category": "stickers", "uso": "_<paquete>_" },
  { "name": "stickerdel", "desc": "Eliminar un sticker de un paquete.", "alias": ["/stickerdel", "/delsticker"], "category": "stickers" },
  { "name": "delpack", "desc": "Eliminar un paquete de stickers completo.", "alias": ["/delpack"], "category": "stickers", "uso": "_<paquete>_" },
  { "name": "delmeta", "desc": "Eliminar los metadatos de tus stickers.", "alias": ["/delmeta", "/delstickermeta"], "category": "stickers" },
  { "name": "addsticker", "desc": "Agregar un sticker a un paquete existente.", "alias": ["/addsticker", "/stickeradd"], "category": "stickers" },

    // Utilidades
     { "name": "upscale", "desc": "Mejora la calidad de una imagen.", "alias": ["/hd", "/upscale"], "category": "utils" },
    {"name": "getpic", "desc": "Ver la foto de perfil de un usuario.", "alias": ["/getpic", "/pfp"], "category": "utils", "uso": "_<mention>_"},
    {"name": "toimg", "desc": "Convertir un sticker en una imagen.", "alias": ["/toimg", "/toimage"], "category": "utils"},
    {"name": "tourl", "desc": "Convierte la imagen en un link.", "alias": ["/tourl"], "category": "utils", "uso": "_<servidor>_" },
    {"name": "get", "desc": "Realiza solicitudes get a páginas web.", "alias": ["/get"], "category": "utils", "uso": "_<url>_"},
    {"name": "removebg", "desc": "Remueve el fondo de una imagen.", "alias": ["/removebg"], "category": "utils" }
];